# _config.yml

title: Your Documentation Title
description: Your documentation description
url: https://k87rte.github.io/clusterDocs

theme: jekyll-theme-material

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: single
      author_profile: false

plugins:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .github
