site_name: test
site_url: https://k87rte.github.io/clusterDocs/

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Introduction: docs/index.md
  - User Guide:
     - FreeSurfer: docs/index_freesurfer.md
